language: go
before_install:
  - go get github.com/mattn/goveralls
script:
- go test ./...
- make build-all
- $GOPATH/bin/goveralls -service=travis-ci
before_deploy:
- curl https://github.com/lindell/github-release-cli/releases/download/1.2.0/github-releaser-travis -L --output github-releaser && chmod +x github-releaser
- export BODY=$(envsubst < ./deployments/CHANGELOG.md)
- export FILES=bin/*
- export RELEASE_NAME=$(echo "Revaboxy v$TRAVIS_TAG" | envsubst)
deploy:
  provider: script
  script: "./github-releaser -draft -verbose"
  skip_cleanup: true
  on:
    tags: true
env:
  global:
    secure: Y/fWZUK29iRG8IdRDh387eMwx4EDziFliyxqV6jv3SWXBp521jTnh+1WHQIZaIVhV+upodu5tILckV7T4dC5kuINlmfyxQzPDnL4dzg/YP4O/BGp9AurTvPxKa+4HSKiyhDd1GyMMh8UCJ77eUmGrBF1Xzlkec12jaEQ8/3NQJLD1ZjeU9jxBeyH0pwFf4kJScl2zhTXARbJOwg9OMM2lKWCuJNmKDU1cmXz2biPnUzm3x8bHu68EPSTGoome059Q+HjbJ39y2eceT1DClaFAjtadOdt5bPL8KLTTgto1w1eTyncb5CmR9onyIZgHrEu/FBt2sL4mM4qmHwgLubxWgXnHPJUs3ZJi/AXu4DWtUyzFPOSg3hZtO0GVXiOQjNhM5nfjKp7oTNdF0jSknUVlG7EOwSRNhBi/sKzgUlBsOvs/BYgTkR5rTQDt4c6n5gL+DlsSs2t0ShKPsiX1M2Vg6cIsdKLUGn+NIJ4ASqo6TrzbydTZhqfDa3xibwYoy0XmkItHMijjws4MeipTi2R6CRU01rL5uaxA6Ec7VDWQPq+G9jAVB+u4d8F06593ttCax3dxt+Lxn29arUZj0TfPVy6h5Mi4tDo5Wo7E+k/+vlgcbevJxVharANq8gMMl3fvtjtVq9eKO8Q5+aM1ZdARzGnBRcoaJh+oH7v1kjJgx4=
