on:
  push:
    tags:
      - "*"

name: Release

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'

      - name: Test
        run: echo $HOME
      - name: Test2
        run: pwd

      - name: Generate release notes
        run: |
          export TAG_NAME=$(echo $GITHUB_REF | sed -E 's/^refs\/tags\///')
          export DOCKER_VERSION=$(echo $TAG_NAME | sed -E 's/v([0-9]\.[0-9]\.[0-9])/\1/')
          envsubst < ./deployments/CHANGELOG.md > /home/runner/CHANGELOG_generated.md

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --release-notes="/home/runner/CHANGELOG_generated.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
